-- Référence MonCasin — trigger_jackpot_roll + RLS
--
-- Le front appelle : supabase.rpc('trigger_jackpot_roll')
-- Réponse attendue : { "ok": true, "round": { "status": "rolling", ... } }
--
-- IMPORTANT : la fonction DOIT être SECURITY DEFINER (comme enter_jackpot_arena),
-- car les policies RLS du repo n'autorisent que SELECT sur jackpot_rounds / jackpot_bets.
-- Sans SECURITY DEFINER, UPDATE/INSERT dans la RPC échoue silencieusement ou avec 42501.
--
-- GRANT obligatoire :
--   grant execute on function public.trigger_jackpot_roll() to authenticated;
-- (optionnel pour tick de secours : anon)
--
-- Colonnes chrono côté client (au moins une valide en status = counting) :
--   started_at timestamptz  → 15 - (now - started_at)
--   ou counting_ends_at     → ceil(ends_at - now)
-- Si les deux sont NULL/invalides, le client forçait 15s en boucle (tirage jamais déclenché).
--
-- RLS jackpot_bets : policy SELECT pour TOUS les joueurs (pas seulement auth.uid() = user_id)
--   create policy jackpot_bets_select on public.jackpot_bets for select using (true);
-- Sinon le front voit pot OK (round) mais 0 gladiateur (mises invisibles).
--
-- Les mises doivent avoir le même round_id que la manche active (jackpot_active_round_id).
--
-- Réponse trigger_jackpot_roll en échec (affichée telle quelle dans la bannière rouge) :
--   { "ok": false, "message": "texte SQL exact" }
--   ou "error" (les deux sont lus par le front).
--
-- Réponse succès attendue par le front :
--   { "ok": true, "round": { "status": "rolling", "winner_id": uuid, "winning_ticket": bigint, ... } }
-- Statuts UI : waiting | counting | rolling | ended (minuscules).
--
-- Colonnes round utilisées par l'UI (non obligatoires toutes à rolling) :
--   rolling : status, winner_id (recommandé), winning_ticket (optionnel), rolling_started_at
--   ended   : + winner_payout, ended_at, tax_pool
-- Le front ne valide PAS ended immédiatement : jackpot_advance_tick ou SQL gère rolling → ended ~4s après.
